/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsNewRouteImport } from './routes/subscriptions/new'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions/$id'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsNewRoute = SubscriptionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscriptionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/new': typeof SubscriptionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/sign-in'
    | '/subscriptions'
    | '/subscriptions/$id'
    | '/subscriptions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/sign-in'
    | '/subscriptions'
    | '/subscriptions/$id'
    | '/subscriptions/new'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/sign-in'
    | '/subscriptions'
    | '/subscriptions/$id'
    | '/subscriptions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/new': {
      id: '/subscriptions/new'
      path: '/new'
      fullPath: '/subscriptions/new'
      preLoaderRoute: typeof SubscriptionsNewRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
  }
}

interface SubscriptionsRouteChildren {
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsNewRoute: typeof SubscriptionsNewRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsNewRoute: SubscriptionsNewRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
